// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using WPFToBlazor.Api;

#nullable disable

namespace WPFToBlazor.Api.Migrations
{
    [DbContext(typeof(DatabaseContext))]
    partial class DatabaseContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "9.0.5");

            modelBuilder.Entity("WPFToBlazor.Data.Model.Bill", b =>
                {
                    b.Property<string>("billId")
                        .HasColumnType("TEXT");

                    b.Property<string>("billData")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("billDate")
                        .HasColumnType("TEXT");

                    b.Property<double>("discount")
                        .HasColumnType("REAL");

                    b.Property<double>("grandTotal")
                        .HasColumnType("REAL");

                    b.Property<double>("subTotal")
                        .HasColumnType("REAL");

                    b.HasKey("billId");

                    b.ToTable("Bills");
                });

            modelBuilder.Entity("WPFToBlazor.Data.Model.BillDataModel", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("BillDate")
                        .HasColumnType("TEXT");

                    b.Property<string>("billData")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<double>("discount")
                        .HasColumnType("REAL");

                    b.Property<double>("grandTotal")
                        .HasColumnType("REAL");

                    b.Property<double>("subTotal")
                        .HasColumnType("REAL");

                    b.HasKey("Id");

                    b.ToTable("BillDataModel");
                });

            modelBuilder.Entity("WPFToBlazor.Data.Model.BillRowItem", b =>
                {
                    b.Property<long>("BillRowItemId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<long?>("BillDataModelId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("BillId")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Comment")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<long>("ItemId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Qty")
                        .HasColumnType("INTEGER");

                    b.Property<int>("RowNo")
                        .HasColumnType("INTEGER");

                    b.Property<double>("Total")
                        .HasColumnType("REAL");

                    b.Property<long?>("TransactionId")
                        .HasColumnType("INTEGER");

                    b.HasKey("BillRowItemId");

                    b.HasIndex("BillDataModelId");

                    b.HasIndex("ItemId");

                    b.HasIndex("TransactionId");

                    b.ToTable("BillRowItem");
                });

            modelBuilder.Entity("WPFToBlazor.Data.Model.Category", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Category");
                });

            modelBuilder.Entity("WPFToBlazor.Data.Model.Item", b =>
                {
                    b.Property<long>("ItemId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Category")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Photo")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("Price")
                        .HasColumnType("INTEGER");

                    b.HasKey("ItemId");

                    b.ToTable("Items");
                });

            modelBuilder.Entity("WPFToBlazor.Data.Model.TestModel", b =>
                {
                    b.Property<int>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("ds")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("id");

                    b.ToTable("TM");
                });

            modelBuilder.Entity("WPFToBlazor.Data.Model.Transaction", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<double>("Total")
                        .HasColumnType("REAL");

                    b.Property<DateTime>("TransactionDateTime")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Transaction");
                });

            modelBuilder.Entity("WPFToBlazor.Data.Model.User", b =>
                {
                    b.Property<int>("UserId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("CashierId")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("IsAdmin")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Password")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("PhoneNumber")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("ProfilePicture")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Username")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("UserId");

                    b.ToTable("Users");
                });

            modelBuilder.Entity("WPFToBlazor.Data.Model.BillRowItem", b =>
                {
                    b.HasOne("WPFToBlazor.Data.Model.BillDataModel", null)
                        .WithMany("BillItems")
                        .HasForeignKey("BillDataModelId");

                    b.HasOne("WPFToBlazor.Data.Model.Item", "Item")
                        .WithMany()
                        .HasForeignKey("ItemId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("WPFToBlazor.Data.Model.Transaction", null)
                        .WithMany("Items")
                        .HasForeignKey("TransactionId");

                    b.Navigation("Item");
                });

            modelBuilder.Entity("WPFToBlazor.Data.Model.BillDataModel", b =>
                {
                    b.Navigation("BillItems");
                });

            modelBuilder.Entity("WPFToBlazor.Data.Model.Transaction", b =>
                {
                    b.Navigation("Items");
                });
#pragma warning restore 612, 618
        }
    }
}
